# Generated by Django 4.1.2 on 2022-10-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_albums_alter_discography_album_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='slug_album',
            field=models.SlugField(default=''),
        ),
    ]
