# Generated by Django 4.1.2 on 2022-11-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_albums_slug_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='discography',
            name='vocals',
            field=models.CharField(choices=[('RE', 'Rod Evans'), ('IG', 'Ian Gillan'), ('DC', 'David Coverdale'), ('JLT', 'Joe Lynn Turner')], default='IG', max_length=3),
        ),
    ]
