# Generated by Django 4.1.2 on 2022-11-06 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_discography_vocals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='discography',
            name='album_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1968), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AddField(
            model_name='discography',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='welcome.label'),
        ),
    ]
