# Generated by Django 4.1.2 on 2022-11-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_mark_discography_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='member_origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.member_origin'),
        ),
    ]
