# Generated by Django 4.1.2 on 2022-11-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_remove_band_member_origin_remove_discography_labels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='album_title',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='slug_album',
        ),
        migrations.AddField(
            model_name='albums',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='welcome.discography'),
        ),
        migrations.AlterField(
            model_name='discography',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='welcome.mark'),
        ),
    ]
