# Generated by Django 4.1.2 on 2022-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_remove_albums_album_title_remove_albums_slug_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(height_field=300, upload_to='', width_field=300)),
            ],
        ),
    ]
