# Generated by Django 4.1.2 on 2022-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_covers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covers',
        ),
    ]
