# Generated by Django 4.1.2 on 2022-11-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0013_delete_covers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='slug',
        ),
    ]
