# Generated by Django 4.1.2 on 2022-11-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
