# Generated by Django 4.1.2 on 2022-11-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0017_delete_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(max_length=180),
        ),
    ]
