# Generated by Django 4.1.2 on 2022-11-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0019_band_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
