# Generated by Django 4.1.2 on 2022-12-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0021_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='portrait',
            field=models.ImageField(default='', upload_to='portraits'),
        ),
        migrations.AddField(
            model_name='discography',
            name='cover',
            field=models.ImageField(default='', upload_to='covers'),
        ),
    ]
