# Generated by Django 4.1.2 on 2022-12-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0022_band_portrait_discography_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mark_foto',
            field=models.ImageField(default='', upload_to='mark_foto'),
        ),
    ]
