# Generated by Django 4.1.2 on 2022-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0023_mark_mark_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='portrait',
            field=models.FileField(default='', upload_to='portraits'),
        ),
    ]
